### ISSUE TITLE
[maintainer wanted] 

### ISSUE THREAD

**Issue by furzeface** [furzeface/grunt-xml-sitemap#11]
[maintainer wanted]

**Comment by MrHyde** [comment]
Our team is interested in maintaining your project and we can dedicate time to fix issues and review pull requests.
Let me know if that works for you

**Comment by furzeface** [comment]
Yes of course @MrHyde - I will make you a contributor or transfer the repository over at some point if that suits you?

I also need to look into allowing others permissions to `npm publish` - do you know how to do this? I don't yet... 

Thank you :smiley:

**Comment by MrHyde** [comment]
Contributing is tottaly ok for us, it's about fixing bugs and promote open source, but you can transfer it to LotusTM organization (unfortunately our repos are mostly private because of NDA :( ) when you feel it's time.
You can add me as an owner https://docs.npmjs.com/cli/owner as far as i know this is the only way right now.

**Comment by furzeface** [comment]
Ok I will do! 

Thanks for the help! :)

**Comment by furzeface** [comment]
Hey @MrHyde - what's your NPM user? I'll add you. I don't mind you having full publish right to this as you've been making your changes :) 

I'm just going to refer to the current version published in my own projects and the projects at work, as this plugin was written with functionality specific to them.

**Comment by mrhyde** [comment]
same as here - [mrhyde](https://www.npmjs.com/~mrhyde)

**Comment by mrhyde** [comment]
Correct link to new repo is actually https://github.com/LotusTM/grunt-sitemap-xml :)
